[build-system]
requires = ['hatchling']
build-backend = 'hatchling.build'

[project]
name = 'pytes'
version = '0.0.1'
authors = [
  { name="Johannes Kreher", email="cerchioditroi@gmail.com"},
]
description = "A simple CLI notes app"
readme = 'README.md'
requires.python = '>=3.9'
classifiers = [
    'Programming Language :: Python :: 3',
    'Operating System :: OS Independent',
]
dependencies = [ 'prompt-toolkit', 'cryptography']
license = 'MIT'
license-files = ['LICEN[CS]E*']

[project.scripts]
pytes = "pytes.main:main"

[project.urls]
Homepage = 'https://github.com/JohannesKreher/pytes'

